//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrawlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.WeaponCharacters = new HashSet<WeaponCharacter>();
        }
    
        public int Id { get; set; }
        public string AccountId { get; set; }
        public string Name { get; set; }
        public int GenderId { get; set; }
        public int ClassId { get; set; }
        public string Avatar { get; set; }
        public int Gold { get; set; }
        public int Level { get; set; }
        public int Experience { get; set; }
        public int Stamina { get; set; }
        public int Strength { get; set; }
        public int Quickness { get; set; }
        public int Block { get; set; }
        public int Evasion { get; set; }
        public int Parry { get; set; }
        public int Vitality { get; set; }
        public int Health { get; set; }
        public int Sword { get; set; }
        public int Mace { get; set; }
        public int Dagger { get; set; }
        public int Spear { get; set; }
        public int Axe { get; set; }
        public int Polearm { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeaponCharacter> WeaponCharacters { get; set; }
    }
}
