//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrawlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponCharacter
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public int WeaponId { get; set; }
        public bool MainHandEquipped { get; set; }
        public bool OffHandEquipped { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Weapon Weapon { get; set; }
    }
}
