//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeaponGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapon
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int WeaponTypeId { get; set; }
        public int MinimumDamage { get; set; }
        public int MaximumDamage { get; set; }
        public int ReqWeaponMastery { get; set; }
        public int Weight { get; set; }
        public bool TournamentReward { get; set; }
        public decimal Price { get; set; }
    
        public virtual WeaponType WeaponType { get; set; }
    }
}
