//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStrawberry.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armor
    {
        public Armor()
        {
            this.EquipmentCharacters = new HashSet<EquipmentCharacter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ArmorTypeId { get; set; }
        public int ArmorValue { get; set; }
        public int Weight { get; set; }
        public bool TourmanemntReward { get; set; }
        public int Price { get; set; }
    
        public virtual ArmorType ArmorType { get; set; }
        public virtual ICollection<EquipmentCharacter> EquipmentCharacters { get; set; }
    }
}
