//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStrawberry.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.Arenas = new HashSet<Arena>();
            this.EquipmentCharacters = new HashSet<EquipmentCharacter>();
            this.CombatLogs = new HashSet<CombatLog>();
        }
    
        public int Id { get; set; }
        public string AccountId { get; set; }
        public string Name { get; set; }
        public int GenderId { get; set; }
        public int ClassId { get; set; }
        public string Avatar { get; set; }
        public int Gold { get; set; }
        public int Level { get; set; }
        public int Experience { get; set; }
        public int Stamina { get; set; }
        public int Strength { get; set; }
        public int Quickness { get; set; }
        public int Block { get; set; }
        public int Evasion { get; set; }
        public int Parry { get; set; }
        public int Vitality { get; set; }
        public int Health { get; set; }
        public int Sword { get; set; }
        public int Mace { get; set; }
        public int Dagger { get; set; }
        public int Spear { get; set; }
        public int Axe { get; set; }
        public int Polearm { get; set; }
        public bool Alive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Class Class { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Arena> Arenas { get; set; }
        public virtual ICollection<EquipmentCharacter> EquipmentCharacters { get; set; }
        public virtual ICollection<CombatLog> CombatLogs { get; set; }
    }
}
