//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStrawberry.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombatLog
    {
        public int Id { get; set; }
        public Nullable<int> Player { get; set; }
        public string Spoiler { get; set; }
        public System.DateTime GameDate { get; set; }
        public byte[] Log { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
