//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStrawberry.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentCharacter
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public Nullable<int> WeaponId { get; set; }
        public Nullable<int> ShieldId { get; set; }
        public Nullable<int> ArmorId { get; set; }
        public bool MainHandEquipped { get; set; }
        public bool OffHandEquipped { get; set; }
        public bool Equipped { get; set; }
    
        public virtual Armor Armor { get; set; }
        public virtual Character Character { get; set; }
        public virtual Shield Shield { get; set; }
        public virtual Weapon Weapon { get; set; }
    }
}
