//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStrawberry.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectStrawberryEntities : DbContext
    {
        public ProjectStrawberryEntities()
            : base("name=ProjectStrawberryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<WeaponType> WeaponTypes { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<Arena> Arenas { get; set; }
        public virtual DbSet<Armor> Armors { get; set; }
        public virtual DbSet<ArmorType> ArmorTypes { get; set; }
        public virtual DbSet<Shield> Shields { get; set; }
        public virtual DbSet<Weapon> Weapons { get; set; }
        public virtual DbSet<EquipmentCharacter> EquipmentCharacters { get; set; }
        public virtual DbSet<CombatLog> CombatLogs { get; set; }
    }
}
